module.exports = course = {
    outline:
        '********',
    objecttives: [
        '********',
    ],
    name: 'MATHEMATICS –II',
    code: '103202',
    credits: 4,
    content: [
        {
            module: '1',
            topics: 'MATRICES: ALGEBRA OF MATRICES, INVERSE AND RANK OF A MATRIX, RANK-NULLITY THEOREM; SYSTEM OF LINEAR EQUATIONS; SYMMETRIC, SKEW-SYMMETRIC AND ORTHOGONAL MATRICES; DETERMINANTS; EIGENVALUES AND EIGENVECTORS; DIAGONALIZATION OF MATRICES; CAYLEY-HAMILTON THEOREM, ORTHOGONAL TRANSFORMATION AND QUADRATIC TO CANONICAL FORMS.',
        },
        {
            module: '2',
            topics: 'NUMERICAL METHODS-I: SOLUTION OF POLYNOMIAL AND TRANSCENDENTAL EQUATIONS – BISECTION METHOD, NEWTON-RAPHSON METHOD AND REGULA-FALSI METHOD. FINITE DIFFERENCES, INTERPOLATION USING NEWTON’S FORWARD AND BACKWARD DIFFERENCE FORMULAE. CENTRAL DIFFERENCE INTERPOLATION: GAUSS’S FORWARD AND BACKWARD FORMULAE. NUMERICAL INTEGRATION: TRAPEZOIDAL RULE AND SIMPSON’S 1/3RD AND 3/8 RULES.',
        },
        {
            module: '3',
            topics: 'NUMERICAL METHODS-II: ORDINARY DIFFERENTIAL EQUATIONS: TAYLOR’S SERIES, EULER AND MODIFIED EULER’S METHODS. RUNGE- KUTTA METHOD OF FOURTH ORDER FOR SOLVING FIRST AND SECOND ORDER EQUATIONS. MILNE’S AND ADAM’S PREDICATOR-CORRECTOR METHODS. PARTIAL DIFFERENTIAL EQUATIONS: FINITE DIFFERENCE SOLUTION TWO DIMENSIONAL LAPLACE EQUATION AND POISSON EQUATION, IMPLICIT AND EXPLICIT METHODS FOR ONE DIMENSIONAL HEAT EQUATION (BENDER-SCHMIDT AND CRANK-NICHOLSON METHODS), FINITE DIFFERENCE EXPLICIT METHOD FOR WAVE EQUATION.',
        },
        {
            module: '4',
            topics: 'TRANSFORM CALCULUS: LAPLACE TRANSFORM, PROPERTIES OF LAPLACE TRANSFORM, LAPLACE TRANSFORM OF PERIODIC FUNCTIONS. FINDING INVERSE LAPLACE TRANSFORM BY DIFFERENT METHODS, CONVOLUTION THEOREM. EVALUATION OF INTEGRALS BY LAPLACE TRANSFORM, SOLVING ODES AND PDES BY LAPLACE TRANSFORM METHOD. FOURIER TRANSFORMS.',
        },
    ],
    books: [
        { name: 'LINEAR ALGEBRA: A MODERN INTRODUCTION', author: 'D. POOLE' },
        { name: 'A TEXT BOOK OF ENGINEERING MATHEMATICS', author: 'N.P. BALI AND M. GOYAL' },
        { name: 'HIGHER ENGINEERING MATHEMATICS', author: 'B.S. GREWAL' },
        { name: 'AN INTRODUCTION TO LINEAR ALGEBRA', author: 'V. KRISHNAMURTHY, V. P. MAINRA AND J. L. ARORA' },
    ],

    outcomes: [
        '*********',
    ],
};
