module.exports = course = {
    outline:
        '********',
    objecttives: [
        '********',
    ],
    name: 'MATHEMATICS –I',
    code: '103102',
    credits: 4,
    content: [
        {
            module: '',
            topics: ' CALCULUS: EVOLUTES AND INVOLUTES; EVALUATION OF DEFINITE AND IMPROPER INTEGRALS; BETA AND GAMMA FUNCTIONS AND THEIR PROPERTIES; APPLICATIONS OF DEFINITE INTEGRALS TO EVALUATE SURFACE AREAS AND VOLUMES OF REVOLUTIONS. ROLLE’S THEOREM,MEAN VALUE THEOREMS, TAYLOR’S AND MACLAURIN THEOREMS WITH REMAINDERS; INDETERMINATE FORMS AND L HOSPITAL S RULE; MAXIMA AND MINIMA.',
        },
        {
            module: '',
            topics: 'SEQUENCES AND SERIES: CONVERGENCE OF SEQUENCE AND SERIES, TESTS FOR CONVERGENCE, POWER SERIES, TAYLOR S SERIES. SERIES FOR EXPONENTIAL, TRIGONOMETRIC AND LOGARITHMIC FUNCTIONS; FOURIER SERIES: HALF RANGE SINE AND COSINE SERIES, PARSEVAL’S THEOREM.',
        },
        {
            module: '',
            topics: 'MULTIVARIABLE CALCULUS: DIFFERENTIATION: LIMIT, CONTINUITY AND PARTIAL DERIVATIVES, DIRECTIONAL DERIVATIVES, TOTAL DERIVATIVE; TANGENT PLANE AND NORMAL LINE; MAXIMA, MINIMA AND SADDLE POINTS; METHOD OF LAGRANGE MULTIPLIERS; GRADIENT, CURL AND DIVERGENCE.',
        },
        {
            module: '',
            topics: ' MULTIVARIABLE CALCULUS: INTEGRATION: MULTIPLE INTEGRATION: DOUBLE AND TRIPLE INTEGRALS (CARTESIAN AND POLAR), CHANGE OF ORDER OF INTEGRATION IN DOUBLE INTEGRALS, CHANGE OF VARIABLES (CARTESIAN TO POLAR), APPLICATIONS: AREAS AND VOLUMES BY (DOUBLE INTEGRATION) CENTER OF MASS AND GRAVITY (CONSTANT AND VARIABLE DENSITIES). THEOREMS OF GREEN, GAUSS AND STOKES, ORTHOGONAL CURVILINEAR COORDINATES, SIMPLE APPLICATIONS INVOLVING CUBES, SPHERE AND RECTANGULAR PARALLELEPIPEDS.',
        },
        {
            module: '',
            topics: 'FIRST ORDER ORDINARY DIFFERENTIAL EQUATIONS: EXACT, LINEAR AND BERNOULLI’S EQUATIONS, EULER’S EQUATIONS, EQUATIONS NOT OF FIRST DEGREE: EQUATIONS SOLVABLE FOR P, EQUATIONS SOLVABLE FOR Y, EQUATIONS SOLVABLE FOR X AND CLAIRAUT’S TYPE.',
        },
        {
            module: '',
            topics: ' ORDINARY DIFFERENTIAL EQUATIONS OF HIGHER ORDER: SECOND ORDER LINEAR DIFFERENTIAL EQUATIONS WITH VARIABLE COEFFICIENTS, METHOD OF VARIATION OF PARAMETERS, CAUCHY-EULER EQUATION; POWER SERIES SOLUTIONS; LEGENDRE POLYNOMIALS, BESSEL FUNCTIONS OF THE FIRST KIND AND THEIR PROPERTIES.',
        },
        {
            module: '',
            topics: 'PARTIAL DIFFERENTIAL EQUATIONS: FIRST ORDER: FIRST ORDER PARTIAL DIFFERENTIAL EQUATIONS, SOLUTIONS OF FIRST ORDER LINEAR AND NON-LINEAR PDES.',
        },
    ],
    books: [
        { name: 'CALCULUS AND ANALYTIC GEOMETRY', author: 'G.B. THOMAS AND R.L. FINNEY' },
        { name: 'ENGINEERING MATHEMATICS', author: 'T. VEERARAJAN' },
        { name: 'HIGHER ENGINEERING MATHEMATICS', author: 'B. V. RAMANA' },
        { name: 'HIGHER ENGINEERING MATHEMATICS', author: 'B.S. GREWAL' },
        { name: 'A TEXT BOOK OF ENGINEERING MATHEMATICS', author: 'N.P. BALI AND M. GOYAL'},
    ],

    outcomes: [
        '*********',
    ],
};
