module.exports = course = {
    outline:
        '*******',
    objecttives: [
        '*******',
    ],
    name: 'ENGLISH',
    code: '100106 & 100206',
    credits: 3,
    content: [
        {
            module: '1',
            topics: 'VOCABULARY BUILDING\nA. THE CONCEPT OF WORD FORMATION\nB. ROOT WORDS FROM FOREIGN LANGUAGES AND THEIR USE IN ENGLISH\nC. ACQUAINTANCE WITH PREFIXES AND SUFFIXES FROM FOREIGN LANGUAGES IN ENGLISH TO FORM DERIVATIVES.\nD. SYNONYMS, ANTONYMS, AND STANDARD ABBREVIATIONS.\nE. AFFIXES, ACRONYMS',
        },
        {
            module: '2',
            topics: 'A. SENTENCE STRUCTURES\nB. USE OF PHRASES AND CLAUSES IN SENTENCES\nC. IMPORTANCE OF PROPER PUNCTUATION\nD. KINDS OF SENTENCES\nE. USE OF TENSE, USE IN CONTEXT AND COHERENCE OF TENSE IN WRITING \nF. USE OF VOICE – ACTIVE/PASSIVE IN SENTENCES\nG. USE OF SPEECH – DIRECT AND INDIRECT SPEECH\nH. FRAMING QUESTIONS- DIRECT, USING MODAL VERBS',
        },
        {
            module: '3',
            topics: ' IDENTIFYING COMMON ERRORS IN WRITING\nA. SUBJECT-VERB AGREEMENT\nB. NOUN-PRONOUN AGREEMENT\nC. MISPLACED MODIFIERS\nD. ARTICLES\nE. PREPOSITIONS\nF. REDUNDANCIES\nG. CLICHÉS\nH. COMMON ENGLISH ERRORS',
        },
        {
            module: '4',
            topics: 'NATURE AND STYLE OF SENSIBLE WRITING\nA. DESCRIBING\nB. DEFINING\nC. CLASSIFYING\nD. PROVIDING EXAMPLES OR EVIDENCE\nE. WRITING INTRODUCTION AND CONCLUSION\nF. ORGANISING PRINCIPLE OF PARAGRAPHS IN DOCUMENTS\nG. ARGUMENT, DESCRIBING/ NARRATING/ PLANNING, DEFINING,CLASSIFYING\nH. LEXICAL RESOURCES, USING SUITABLE LANGUAGE REGISTER\nI. COHERENCE, WRITING INTRODUCTION, BODY AND CONCLUSION, TECHNIQUES FOR WRITING PRECISELY,GRAMMAR AND ACCURACY',
        },
        {
            module: '5',
            topics: 'WRITING PRACTICES\nA. COMPREHENSION\nB. FORMAL LETTER WRITING/ APPLICATION/ REPORT WRITING/ WRITING MINUTES OF MEETINGS \nC. ESSAY WRITING\nD. FORMAL EMAIL WRITING \nE. RESUME/ CV WRITING, COVER LETTER, \nF. STATEMENT OF PURPOSE',
        },
        {
            module: '6',
            topics: 'ORAL COMMUNICATION \n(THIS UNIT INVOLVES INTERACTIVE PRACTICE SESSIONS IN LANGUAGE LAB)\nA. LISTENING COMPREHENSION\nB. PRONUNCIATION, INTONATION, STRESS AND RHYTHM\nC. COMMON EVERYDAY SITUATIONS: CONVERSATIONS AND DIALOGUES\nD. COMMUNICATION AT WORKPLACE\nE. INTERVIEWS\nF. FORMAL PRESENTATIONS\nG. ACQUAINTING STUDENTS WITH IPA SYMBOLS\nH. PHONETICS (BASIC) \nI. SOUNDS – VOWELS, CONSONANTS\nJ. CLEARING MOTHER TONGUE INFLUENCE \nK. CLEARING REDUNDANCIES AND COMMON ERRORS RELATED TO INDIANISMS \nL. GROUP DISCUSSION \nM. EXPRESSING OPINIONS\nN. COHERENCE AND FLUENCY IN SPEECH',
        },
        {
            module: '7',
            topics: 'READING SKILLS\nA. READING COMPREHENSION,\nB. PARAGRAPH READING BASED ON PHONETIC SOUNDS/ INTONATION',
        },
        {
            module: '8',
            topics: 'PROFESSIONAL SKILLS\nA. TEAM BUILDING \nB. SOFT SKILLS AND ETIQUETTES',
        },
        {
            module: '9',
            topics: 'ACQUAINTANCE WITH TECHNOLOGY-AIDED LANGUAGE LEARNING\nA. USE OF COMPUTER SOFTWARE (GRAMMARLY, GINGER…)\nB. USE OF SMARTPHONE APPLICATIONS (DUOLINGO, BUSUU…)',
        },
        {
            module: '10',
            topics: ' ACTIVITIES\nA. NARRATIVE CHAIN\nB. DESCRIBING/ NARRATING \nC. WRITING ESSAYS IN RELAY \nD. PEER/ GROUP ACTIVITIES\nE. BRAINSTORMING VOCABULARY \nF. CUE / FLASH CARDS FOR VOCABULARY \nG. DEBATES ',
        },
    ],
    books: [
        { name: 'PRACTICAL ENGLISH USAGE', author: 'MICHAEL SWAN' },
        { name: 'REMEDIAL ENGLISH GRAMMAR', author: 'F.T. WOOD' },
        { name: 'ON WRITING WELL', author: 'WILLIAM ZINSSER' },
        { name: 'COMMUNICATION SKILLS', author: 'SANJAY KUMAR AND PUSHPLATA' },
    ],

    outcomes: [
        'THE STUDENT WILL ACQUIRE BASIC PROFICIENCY IN ENGLISH INCLUDING READING AND LISTENING COMPREHENSION, WRITING AND SPEAKING SKILLS.',
    ],
};
