module.exports = course = {
    outline:
        'LIST OF EXPERIMENTS/DEMONSTRATIONS:\n BASIC SAFETY PRECAUTIONS. INTRODUCTION AND USE OF MEASURING INSTRUMENTS – VOLTMETER, AMMETER, MULTI-METER, OSCILLOSCOPE. REAL-LIFE RESISTORS, CAPACITORS AND INDUCTORS.\n MEASURING THE STEADY-STATE AND TRANSIENT TIME-RESPONSE OF R-L, R-C, AND R-L-C CIRCUITS TO A STEP CHANGE IN VOLTAGE (TRANSIENT MAY BE OBSERVED ON A STORAGE OSCILLOSCOPE). SINUSOIDAL STEADY STATE RESPONSE OF R-L, AND RC CIRCUITS – IMPEDANCE CALCULATION AND VERIFICATION. OBSERVATION OF PHASEDIFFERENCES BETWEEN CURRENT AND VOLTAGE. RESONANCE IN R-L-C CIRCUITS.\n TRANSFORMERS: OBSERVATION OF THE NO-LOAD CURRENT WAVEFORM ON AN OSCILLOSCOPE (NON- SINUSOIDAL WAVE-SHAPE DUE TO B-H CURVE NONLINEARITY SHOULD BE SHOWN ALONG WITH A DISCUSSION ABOUT HARMONICS). LOADING OF A TRANSFORMER: MEASUREMENT OF PRIMARY AND SECONDARY VOLTAGES AND CURRENTS, AND POWER.\n THREE-PHASE TRANSFORMERS: STAR AND DELTA CONNECTIONS. VOLTAGE AND CURRENT RELATIONSHIPS (LINE-LINE VOLTAGE, PHASE-TO-NEUTRAL VOLTAGE, LINE AND PHASE CURRENTS). PHASE-SHIFTS BETWEEN THE PRIMARY AND SECONDARYSIDE. CUMULATIVE THREE-PHASE POWER IN BALANCED THREE-PHASE CIRCUITS.\n DEMONSTRATION OF CUT-OUT SECTIONS OF MACHINES: DC MACHINE (COMMUTATOR BRUSH ARRANGEMENT), INDUCTION MACHINE (SQUIRREL CAGE ROTOR), SYNCHRONOUS MACHINE (FIELD WINGING - SLIP RING ARRANGEMENT) AND SINGLE-PHASE INDUCTION MACHINE.\n TORQUE SPEED CHARACTERISTIC OF SEPARATELY EXCITED DC MOTOR.\n SYNCHRONOUS SPEED OF TWO AND FOUR-POLE, THREE-PHASE INDUCTION MOTORS. DIRECTION REVERSAL BY CHANGE OF PHASE-SEQUENCE OF CONNECTIONS. TORQUE SLIP CHARACTERISTIC OF AN INDUCTION MOTOR. GENERATOR OPERATION OF AN INDUCTION MACHINE DRIVEN AT SUPER- SYNCHRONOUS SPEED.\n SYNCHRONOUS MACHINE OPERATING AS A GENERATOR: STAND-ALONE OPERATION WITHA LOAD. CONTROL OF VOLTAGE THROUGH FIELD EXCITATION.\n DEMONSTRATION OF (A) DC-DC CONVERTERS (B) DC-AC CONVERTERS – PWM WAVEFORM (C) THE USE OF DC-AC CONVERTER FOR SPEED CONTROL OF AN INDUCTION MOTOR AND (D) COMPONENTS OF LT SWITCHGEAR.',
    objecttives: [
        '**********',
    ],
    name: 'BASIC ELECTRICAL ENGINEERING and BASIC ELECTRICAL ENGINEERING LAB.',
    code: '100101 & 100201',
    credits: 5,
    content: [
        {
            module: '1',
            topics: 'DC CIRCUITS: ELECTRICAL CIRCUIT ELEMENTS (R, L AND C), VOLTAGE AND CURRENT SOURCES, KIRCHHOFF CURRENT AND VOLTAGE LAWS, ANALYSIS OF SIMPLE CIRCUITS WITH DC EXCITATION. STAR-DELTA CONVERSION, NETWORK THEOREMS (SUPERPOSITION, THEVENIN, NORTON AND MAXIMUM POWER TRANSFER THEOREMS). TIME-DOMAIN ANALYSIS OF FIRST ORDER RL AND RC CIRCUITS',
        },
        {
            module: '2',
            topics: 'AC CIRCUITS: REPRESENTATION OF SINUSOIDAL WAVEFORMS, PEAK, RMS AND AVERAGE VALUES (FORM FACTOR AND PEAK FACTOR), IMPEDANCE OF SERIES AND PARALLEL CIRCUIT, PHASOR REPRESENTATION, REAL POWER, REACTIVE POWER, APPARENT POWER, POWER FACTOR, POWER TRIANGLE. ANALYSIS OF SINGLE-PHASE AC CIRCUITS CONSISTING OF R, L, C, RL, RC, RLC COMBINATIONS (SERIES AND PARALLEL), RESONANCE. THREE-PHASE BALANCED CIRCUITS, VOLTAGE AND CURRENT RELATIONS IN STAR AND DELTA CONNECTIONS.',
        },
        {
            module: '3',
            topics: 'MAGNETIC CIRCUITS: INTRODUCTION, SERIES AND PARALLEL MAGNETIC CIRCUITS, ANALYSIS OF SERIES AND PARALLEL MAGNETIC CIRCUITS.',
        },
        {
            module: '4',
            topics: 'TRANSFORMERS: MAGNETIC MATERIALS, BH CHARACTERISTICS, IDEAL AND PRACTICAL TRANSFORMER, EMF EQUATION, EQUIVALENT CIRCUIT, LOSSES IN TRANSFORMERS, REGULATION AND EFFICIENCY. AUTO-TRANSFORMER AND THREE-PHASE TRANSFORMER CONNECTIONS.',
        },
        {
            module: '5',
            topics: 'ELECTRICAL MACHINES: CONSTRUCTION, WORKING, TORQUE-SPEED CHARACTERISTIC AND SPEED CONTROL OF SEPARATELY EXCITED DC MOTOR. GENERATION OF ROTATING MAGNETIC FIELDS, CONSTRUCTION AND WORKING OF A THREE-PHASE INDUCTION MOTOR, SIGNIFICANCE OF TORQUE-SLIP CHARACTERISTIC. LOSS COMPONENTS AND EFFICIENCY, STARTING AND SPEED CONTROL OF INDUCTION MOTOR. CONSTRUCTION AND WORKING OF SYNCHRONOUS GENERATORS. ',
        },
        {
            module: '6',
            topics: 'ELECTRICAL INSTALLATIONS: COMPONENTS OF LT SWITCHGEAR: SWITCH FUSE UNIT (SFU), MCB, ELCB, MCCB, TYPES OF WIRES AND CABLES, EARTHING. TYPES OF BATTERIES, IMPORTANT CHARACTERISTICS FOR BATTERIES. ELEMENTARY CALCULATIONS FOR ENERGY CONSUMPTION, POWER FACTOR IMPROVEMENT AND BATTERY BACKUP.',
        },
    ],
    books: [
        { name: 'BASIC ELECTRICAL ENGINEERING', author: 'D. P. KOTHARI AND I. J. NAGRATH' },
        { name: 'BASIC ELECTRICAL ENGINEERING', author: 'D. C. KULSHRESHTHA' },
        { name: 'FUNDAMENTALS OF ELECTRICAL ENGINEERING', author: 'L. S. BOBROW' },
        { name: 'BASIC ELECTRICAL ENGINEERING', author: 'V.K. MEHTA AND ROHIT MEHTA' },
    ],

    outcomes: [
        '1. TO UNDERSTAND AND ANALYZE BASIC ELECTRIC AND MAGNETIC CIRCUITS',
        '2. TO STUDY THE WORKING PRINCIPLES OF ELECTRICAL MACHINES AND POWER CONVERTERS.',
        '3. TO INTRODUCE THE COMPONENTS OF LOW VOLTAGE ELECTRICAL INSTALLATIONS',
        '4. GET AN EXPOSURE TO COMMON ELECTRICAL COMPONENTS AND THEIR RATINGS.',
        '5. MAKE ELECTRICAL CONNECTIONS BY WIRES OF APPROPRIATE RATINGS.',
        '6. UNDERSTAND THE USAGE OF COMMON ELECTRICAL MEASURING INSTRUMENTS.',
        '7. UNDERSTAND THE BASIC CHARACTERISTICS OF TRANSFORMERS AND ELECTRICAL MACHINES.',
        '8. GET AN EXPOSURE TO THE WORKING OF POWER ELECTRONIC CONVERTERS ',
    ],
};
