module.exports = course = {
    outline:
        ' DETERMINATION OF SURFACE TENSION AND VISCOSITY.\n THIN LAYER CHROMATOGRAPHY.\n ION EXCHANGE COLUMN FOR REMOVAL OF HARDNESS OF WATER.\n DETERMINATION OF CHLORIDE CONTENT OF WATER.\n COLLIGATIVE PROPERTIES USING FREEZING POINT DEPRESSION.\n DETERMINATION OF THE RATE CONSTANT OF A REACTION.\n DETERMINATION OF CELL CONSTANT AND CONDUCTANCE OF SOLUTIONS.\n POTENTIOMETRY - DETERMINATION OF REDOX POTENTIALS AND EMFS.\n SYNTHESIS OF A POLYMER/DRUG.\n SAPONIFICATION/ACID VALUE OF AN OIL.\n CHEMICAL ANALYSIS OF A SALT.\n LATTICE STRUCTURES AND PACKING OF SPHERES.\n MODELS OF POTENTIAL ENERGY SURFACES.\n CHEMICAL OSCILLATIONS- IODINE CLOCK REACTION.\n DETERMINATION OF THE PARTITION COEFFICIENT OF A SUBSTANCE BETWEEN TWO IMMISCIBLE LIQUIDS.\n ADSORPTION OF ACETIC ACID BY CHARCOAL.\n USE OF THE CAPILLARY VISCOSIMETERS TO THE DEMONSTRATE OF THE ISOELECTRIC POINT AS THE PH OF MINIMUM VISCOSITY FOR GELATIN SOLS AND/OR COAGULATION OF THE WHITE PART OF EGG.',
    objecttives: [
        '*********',
    ],
    name: 'CHEMISTRY and CHEMISTRY LAB.',
    code: '100103 & 100203',
    credits: 5.5,
    content: [
        {
            module: '1',
            topics: 'ATOMIC AND MOLECULAR STRUCTURE: FAILURE OF CLASSICAL NEWTONIAN AND MAXWELL WAVE MECHANICS TO EXPLAIN PROPERTIES OF PARTICLES AT ATOMIC AND SUB-ATOMIC LEVEL; ELECTROMAGNETIC RADIATION, DUAL NATURE OF ELECTRON AND ELECTROMAGNETIC RADIATION, PLANKS THEORY, PHOTOELECTRIC EFFECT AND HEISENBERG UNCERTAINTY PRINCIPLE. FAILURE OF EARLIER THEORIES TO EXPLAIN CERTAIN PROPERTIES OF MOLECULES LIKE PARAMAGNETIC PROPERTIES. PRINCIPLES FOR COMBINATION OF ATOMIC ORBITALS TO FORM MOLECULAR ORBITALS. FORMATION OF HOMO AND HETERO DIATOMIC MOLECULES AND PLOTS OF ENERGY LEVEL DIAGRAM OF MOLECULAR ORBITALS. COORDINATION NUMBERS AND GEOMETRIES, ISOMERISM IN TRANSITIONAL METAL COMPOUNDS, CRYSTAL FIELD THEORY AND THE ENERGY LEVEL DIAGRAMS FOR TRANSITION METAL IONS AND THEIR MAGNETIC PROPERTIES. ',
        },
        {
            module: '2',
            topics: ' SPECTROSCOPIC TECHNIQUES AND APPLICATIONS: PRINCIPLES OF VIBRATIONAL AND ROTATIONAL SPECTROSCOPY AND SELECTION RULES FOR APPLICATION IN DIATOMIC MOLECULES. ELEMENTARY IDEA OF ELECTRONIC SPECTROSCOPY. UV-VIS SPECTROSCOPY WITH RELATED RULES AND ITS APPLICATIONS. FLUORESCENCE AND ITS APPLICATIONS IN MEDICINE. BASIC PRINCIPLE OF NUCLEAR MAGNETIC RESONANCE AND ITS APPLICATION. BASICS OF MAGNETIC RESONANCE IMAGING.',
        },
        {
            module: '3',
            topics: 'INTERMOLECULAR FORCES AND PROPERTIES OF GASES: IONIC, DIPOLAR AND VAN DER WAALS INTERACTIONS. EQUATIONS OF STATE OF IDEAL AND REAL GASES, DEVIATION FROM IDEAL BEHAVIOUR. VANDER WAAL GAS EQUATION.',
        },
        {
            module: '4',
            topics: 'USE OF FREE ENERGY IN CHEMICAL EQUILIBRIA & WATER CHEMISTRY: THERMODYNAMIC FUNCTIONS: ENERGY, ENTHALPY ENTROPY AND FREE ENERGY. EQUATIONS TO INTERRELATE THERMODYNAMIC PROPERTIES. FREE ENERGY, EMF. AND CELL POTENTIALS, THE NERNST EQUATION AND APPLICATIONS. CORROSION. USE OF FREE ENERGY CONSIDERATIONS IN METALLURGY THROUGH ELLINGHAM DIAGRAMS. SOLUBILITY EQUILIBRIA.WATER CHEMISTRY, HARD AND SOFT WATER. PARAMETERS OF QUALITY OF WATER TO BE USED IN DIFFERENT INDUSTRIES AS FOR DRINKING WATER. CALCULATION OF HARDNESS OF WATER IN ALL UNITS. ESTIMATION OF HARDNESS USING EDTA AND ALKALINITY METHOD REMOVAL OF HARDNESS BY SODA LIME AND ION EXCHANGE METHOD INCLUDING ZEOLITE METHOD',
        },
        {
            module: '5',
            topics: 'PERIODIC PROPERTIES: EFFECTIVE NUCLEAR CHARGE, PENETRATION OF ORBITALS, VARIATIONS OF S, P, D AND F ORBITAL ENERGIES OF ATOMS IN THE PERIODIC TABLE, ELECTRONIC CONFIGURATIONS, ATOMIC AND IONIC SIZES, IONIZATION ENERGIES, ELECTRON AFFINITY AND ELECTRONEGATIVITY, POLARIZABILITY, ACID, BASE, PRINCIPLE OF HSAB THEORY, OXIDATION STATES, HYBRIDIZATION AND MOLECULAR GEOMETRIES.',
        },
        {
            module: '6',
            topics: 'STEREOCHEMISTRY:  REPRESENTATIONS OF 3-D STRUCTURES, STRUCTURAL ISOMERS AND STEREOISOMERS, CONFIGURATIONS AND SYMMETRY AND CHIRALITY, ENANTIOMERS, DIASTEREOMERS, OPTICAL ACTIVITY, ABSOLUTE CONFIGURATIONS AND CONFORMATIONAL ANALYSIS.',
        },
        {
            module: '7',
            topics: 'ORGANIC REACTIONS AND SYNTHESIS OF A DRUG MOLECULE: INTRODUCTION TO INTERMEDIATES AND REACTIONS INVOLVING SUBSTITUTION, ADDITION, ELIMINATION, OXIDATION- REDUCTION, DIELS ELDER CYCLIZATION AND EPOXIDE RING OPENINGS REACTIONS. SYNTHESIS OF A COMMONLY USED DRUG MOLECULE LIKE ASPIRIN.',
        },
    ],
    books: [
        { name: 'UNIVERSITY CHEMISTRY', author: 'B. H. MAHAN' },
        { name: 'CHEMISTRY: PRINCIPLES AND APPLICATIONS', author: 'M. J. SIENKO AND R. A. PLANE' },
        { name: 'FUNDAMENTALS OF MOLECULAR SPECTROSCOPY', author: 'C. N. BANWELL' },
        { name: 'ORGANIC CHEMISTRY: STRUCTURE AND FUNCTION', author: 'K. P. C. VOLHARDT AND N. E.SCHORE,' },
    ],

    outcomes: [
        'THE CONCEPTS DEVELOPED IN THIS COURSE WILL AID IN QUANTIFICATION OF SEVERAL CONCEPTS IN CHEMISTRY THAT HAVE BEEN INTRODUCED AT THE 10+2 LEVELS IN SCHOOLS. TECHNOLOGY IS BEING INCREASINGLY BASED ON THE ELECTRONIC, ATOMIC AND MOLECULAR LEVEL MODIFICATIONS.QUANTUM THEORY IS MORE THAN 100 YEARS OLD AND TO UNDERSTAND PHENOMENA AT NANOMETER LEVELS, ONE HAS TO BASE THE DESCRIPTION OF ALL CHEMICAL PROCESSES AT MOLECULAR LEVELS. THE COURSE WILL ENABLE THE STUDENT TO: ANALYSE MICROSCOPIC CHEMISTRY IN TERMS OF ATOMIC AND MOLECULAR ORBITALS AND INTERMOLECULAR FORCES.RATIONALISE BULK PROPERTIES AND PROCESSES USING THERMODYNAMIC CONSIDERATIONS. DISTINGUISH THE RANGES OF THE ELECTROMAGNETIC SPECTRUM USED FOR EXCITING DIFFERENT MOLECULAR ENERGY LEVELS IN VARIOUS SPECTROSCOPIC TECHNIQUES RATIONALISE PERIODIC PROPERTIES SUCH AS IONIZATION POTENTIAL, ELECTRONEGATIVITY, OXIDATION STATES AND ELECTRONEGATIVITY.LIST MAJOR CHEMICAL REACTIONS THAT ARE USED IN THE SYNTHESIS OF MOLECULES.',
        'THE CHEMISTRY LABORATORY COURSE WILL CONSIST OF EXPERIMENTS ILLUSTRATING THE PRINCIPLES OF CHEMISTRY RELEVANT TO THE STUDY OF SCIENCE AND ENGINEERING. THE STUDENTS WILL LEARN TO: ESTIMATE RATE CONSTANTS OF REACTIONS FROM CONCENTRATION OF REACTANTS/PRODUCTS AS A FUNCTION OF TIME MEASURE MOLECULAR/SYSTEM PROPERTIES SUCH AS SURFACE TENSION, VISCOSITY, CONDUCTANCE OF SOLUTIONS, REDOX POTENTIALS, CHLORIDE CONTENT OF WATER, ETC SYNTHESIZE A SMALL DRUG MOLECULE AND ANALYSE A SALT SAMPLE',
    ],
};
