module.exports = course = {
    outline:
        '1. MACHINE SHOP (10 HOURS) AND FITTING SHOP (8 HOURS) \n2. CARPENTRY (6 HOURS) \n3. WELDING SHOP (8 HOURS) (ARC WELDING 4 HRS + GAS WELDING 4 HRS) \n4. CASTING (8 HOURS) AND SMITHY (6 HOURS) \n5. PLASTIC MOULDING & GLASS CUTTING (6 HOURS) \n6. 3-D PRINTING OF DIFFERENT MODELS (8 HOURS)\nEXAMINATIONS COULD INVOLVE THE ACTUAL FABRICATION OF SIMPLE COMPONENTS,UTILIZING ONE OR MORE OF THE TECHNIQUES COVERED ABOVE.',
    objecttives: [
        '**********',
    ],
    name: 'WORKSHOP MANUFACTURING PRACTICES ',
    code: ' 100105 & 100205',
    credits: 3,
    content: [
        {
            module: '0',
            topics: '1. MANUFACTURING METHODS-CASTING, FORMING, MACHINING, JOINING, ADVANCED MANUFACTURING METHODS (3 LECTURES) \n2. CNC MACHINING, ADDITIVE MANUFACTURING (1 LECTURE) \n3. FITTING OPERATIONS & POWER TOOLS (1 LECTURE) \n4. CARPENTRY (1 LECTURE) \n5. PLASTIC MOULDING, GLASS CUTTING (1 LECTURE) \n6. METAL CASTING (1 LECTURE) \n7. WELDING (ARC WELDING & GAS WELDING), BRAZING, SOLDERING (2 LECTURE)',
        },
    ],
    books: [
        { name: 'ELEMENTS OF WORKSHOP TECHNOLOGY, VOL. I', author: 'HAJRA CHOUDHURY S.K., HAJRA CHOUDHURY A.K. AND NIRJHAR ROY S.K.' },
        { name: 'MANUFACTURING ENGINEERING AND TECHNOLOGY', author: 'KALPAKJIAN S. AND STEVEN S. SCHMID' },
        { name: 'MANUFACTURING TECHNOLOGY – I', author: 'GOWRI P. HARIHARAN AND A. SURESH BABU' },
        { name: 'MANUFACTURING TECHNOLOGY VOL. I AND VOL. II', author: 'RAO P.N.' },
    ],

    outcomes: [
        'UPON COMPLETION OF THIS COURSE, THE STUDENTS WILL GAIN KNOWLEDGE OF THE DIFFERENT MANUFACTURING PROCESSES WHICH ARE COMMONLY EMPLOYED IN THE INDUSTRY, TO FABRICATE COMPONENTS USING DIFFERENT MATERIALS. ',
        ' UPON COMPLETION OF THIS LABORATORY COURSE, STUDENTS WILL BE ABLE TO FABRICATE COMPONENTS WITH THEIR OWN HANDS. \n THEY WILL ALSO GET PRACTICAL KNOWLEDGE OF THE DIMENSIONAL ACCURACIES AND DIMENSIONAL TOLERANCES POSSIBLE WITH DIFFERENT MANUFACTURING PROCESSES. \n BY ASSEMBLING DIFFERENT COMPONENTS, THEY WILL BE ABLE TO PRODUCE SMALL DEVICES OF THEIR INTEREST. BY ASSEMBLING DIFFERENT COMPONENTS, THEY WILL BE ABLE TO PRODUCE SMALL DEVICES OF THEIR INTEREST.',
    ],
};
