module.exports = course = {
    outline:
        'Laboratory Experiments included.',
    objecttives: [
        '**********',
    ],
    name: 'PHYSICS ',
    code: '103201',
    credits: 5.5,
    content: [
        {
            module: '1',
            topics: ' WAVES: MECHANICAL AND ELECTRICAL SIMPLE HARMONIC OSCILLATORS, DAMPED HARMONIC OSCILLATOR, FORCED MECHANICAL AND ELECTRICAL OSCILLATORS, IMPEDANCE, STEADY STATE MOTION OF FORCED DAMPED HARMONIC OSCILLATOR',
        },
        {
            module: '2',
            topics: 'NON-DISPERSIVE TRANSVERSE AND LONGITUDINAL WAVES: TRANSVERSE WAVE ON A STRING, THE WAVE EQUATION ON A STRING, HARMONIC WAVES, REFLECTION AND TRANSMISSION OF WAVES AT A BOUNDARY, IMPEDANCE MATCHING, STANDING WAVES AND THEIR EIGEN FREQUENCIES, LONGITUDINAL WAVES AND THE WAVE EQUATION FOR THEM, ACOUSTICS WAVES',
        },
        {
            module: '3',
            topics: ' LIGHT AND OPTICS: LIGHT AS AN ELECTROMAGNETIC WAVE AND FRESNEL EQUATIONS, REFLECTANCE AND TRANSMITTANCE, BREWSTER’S ANGLE, TOTAL INTERNAL REFLECTION, AND EVANESCENT WAVE. MIRRORS AND LENSES AND OPTICAL INSTRUMENTS BASED ON THEM',
        },
        {
            module: '4',
            topics: 'WAVE OPTICS: HUYGENS’ PRINCIPLE, SUPERPOSITION OF WAVES AND INTERFERENCE OF LIGHT BY WAVEFRONT SPLITTING AND AMPLITUDE SPLITTING; YOUNG’S DOUBLE SLIT EXPERIMENT, NEWTON’S RINGS, MICHELSON INTERFEROMETER, MACH ZEHNDER INTERFEROMETER. FARUNHOFER DIFFRACTION FROM A SINGLE SLIT AND A CIRCULAR APERTURE, THE RAYLEIGH CRITERION FOR LIMIT OF RESOLUTION AND ITS APPLICATION TO VISION; DIFFRACTION GRATINGS AND THEIR RESOLVING POWER',
        },
        {
            module: '5',
            topics: ' LASERS: EINSTEIN’S THEORY OF MATTER RADIATION INTERACTION AND A AND B COEFFICIENTS; AMPLIFICATION OF LIGHT BY POPULATION INVERSION, DIFFERENT TYPES OF LASERS: GAS LASERS (HE-NE, CO2), SOLID-STATE LASERS (RUBY, NEODYMIUM), DYE LASERS; PROPERTIES OF LASER BEAMS: MONO-CHROMATICITY',
        },
        {
            module: '6',
            topics: 'INTRODUCTION TO QUANTUM MECHANICS: WAVE NATURE OF PARTICLES, TIME-DEPENDENT AND TIME-INDEPENDENT SCHRODINGER EQUATION FOR WAVE FUNCTION, BORN INTERPRETATION, PROBABILITY CURRENT, EXPECTATION VALUES, FREE-PARTICLE WAVE FUNCTION AND WAVE-PACKETS, UNCERTAINTY PRINCIPLE.',
        },
        {
            module: '7',
            topics: 'SOLUTION OF WAVE EQUATION: SOLUTION OF STATIONARY-STATE SCHRODINGER EQUATION FOR ONE DIMENSIONAL PROBLEMS–PARTICLE IN A BOX, PARTICLE IN ATTRACTIVE DELTA-FUNCTION POTENTIAL, SQUARE-WELL POTENTIAL, LINEAR HARMONIC OSCILLATOR. SCATTERING FROM A POTENTIAL BARRIER AND TUNNELING; RELATED EXAMPLES LIKE ALPHA- DECAY, FIELD-IONIZATION AND SCANNING TUNNELING MICROSCOPE, TUNNELING IN SEMICONDUCTOR STRUCTURES. THREEDIMENSIONAL PROBLEMS: PARTICLE IN THREE DIMENSIONAL BOX AND RELATED EXAMPLES.',
        },
        {
            module: '8',
            topics: 'INTRODUCTION TO SOLIDS AND SEMICONDUCTORS: FREE ELECTRON THEORY OF METALS, FERMI LEVEL, DENSITY OF STATES IN 1, 2 AND 3 DIMENSIONS, BLOCH’S THEOREM FOR PARTICLES IN A PERIODIC POTENTIAL, KRONIGPENNEY MODEL AND ORIGIN OF ENERGY BANDS.\nTYPES OF ELECTRONIC MATERIALS: METALS, SEMICONDUCTORS, AND INSULATORS. INTRINSIC AND EXTRINSIC SEMICONDUCTORS, DEPENDENCE OF FERMI LEVEL ON CARRIERCONCENTRATION AND TEMPERATURE (EQUILIBRIUM CARRIER STATISTICS), CARRIER GENERATION AND RECOMBINATION, CARRIER TRANSPORT: DIFFUSION AND DRIFT, P -N JUNCTION.',
        },
    ],
    books: [
        { name: 'VIBRATIONS AND WAVES IN PHYSICS', author: 'G. MAIN' },
        { name: 'THE PHYSICS OF VIBRATIONS AND WAVES', author: 'H. J. PAIN' },
        { name: 'OPTICS', author: 'E. HECHT' },
        { name: 'PRINCIPLES OF LASERS', author: 'O. SVELTO' },
    ],

    outcomes: [
        '*********',
    ],
};
