module.exports = course = {
    outline:
        ' INTRODUCTION TO ENGINEERING DESIGN AND ITS PLACE IN SOCIETY\n EXPOSURE TO THE VISUAL ASPECTS OF ENGINEERING DESIGN\n EXPOSURE TO ENGINEERING GRAPHICS STANDARDS\n EXPOSURE TO SOLID MODELLING\n EXPOSURE TO COMPUTER-AIDED GEOMETRIC DESIGN\n EXPOSURE TO CREATING WORKING DRAWINGS\n EXPOSURE TO ENGINEERING COMMUNICATION',
    objecttives: [
        ' TO PREPARE YOU TO DESIGN A SYSTEM, COMPONENT, OR PROCESS TO MEET DESIRED NEEDS WITHIN REALISTIC CONSTRAINTS SUCH AS ECONOMIC, ENVIRONMENTAL, SOCIAL, POLITICAL, ETHICAL, HEALTH AND SAFETY, MANUFACTURABILITY, AND SUSTAINABILITY \n TO PREPARE YOU TO COMMUNICATE EFFECTIVELY\n TO PREPARE YOU TO USE THE TECHNIQUES, SKILLS, AND MODERN ENGINEERING TOOLS NECESSARY FOR ENGINEERING PRACTICE',
    ],
    name: 'ENGINEERING GRAPHICS & DESIGN and ENGINEERING GRAPHICS & DESIGN LAB.',
    code: ' 100102 & 100202',
    credits: 3,
    content: [
        {
            module: '0',
            topics: 'TRADITIONAL ENGINEERING GRAPHICS: PRINCIPLES OF ENGINEERING GRAPHICS; ORTHOGRAPHIC PROJECTION; DESCRIPTIVE GEOMETRY; DRAWING PRINCIPLES; ISOMETRIC PROJECTION; SURFACE DEVELOPMENT; PERSPECTIVE; READING A DRAWING; SECTIONAL VIEWS; DIMENSIONING & TOLERANCES; TRUE LENGTH, ANGLE; INTERSECTION, SHORTEST DISTANCE. \nCOMPUTER GRAPHICS: ENGINEERING GRAPHICS SOFTWARE; -SPATIAL TRANSFORMATIONS; ORTHOGRAPHIC PROJECTIONS; MODEL VIEWING; CO-ORDINATE SYSTEMS; MULTI-VIEW PROJECTION; EXPLODED ASSEMBLY; MODEL VIEWING; ANIMATION; SPATIAL MANIPULATION; SURFACE MODELLING; SOLID MODELLING, INTRODUCTION TO BUILDING INFORMATION MODELLING (BIM).',
        },
        {
            module: '1',
            topics: 'INTRODUCTION TO ENGINEERING DRAWING: PRINCIPLES OF ENGINEERING GRAPHICS AND THEIR SIGNIFICANCE, USAGE OF DRAWING INSTRUMENTS, LETTERING, CONIC SECTIONS INCLUDING THE RECTANGULAR HYPERBOLA (GENERAL METHOD ONLY); CYCLOID, EPICYCLOID, HYPOCYCLOID AND INVOLUTE; SCALES – PLAIN, DIAGONAL AND VERNIER SCALES',
        },
        {
            module: '2',
            topics: 'ORTHOGRAPHIC PROJECTIONS: PRINCIPLES OF ORTHOGRAPHIC PROJECTIONS-CONVENTIONS -PROJECTIONS OF POINTS AND LINES INCLINED TO BOTH PLANES; PROJECTIONS OF PLANES INCLINED PLANES -AUXILIARY PLANES',
        },
        {
            module: '3',
            topics: ' PROJECTIONS OF REGULAR SOLIDS: THOSE INCLINED TO BOTH THE PLANES- AUXILIARY VIEWS; DRAW SIMPLE ANNOTATION, DIMENSIONING AND SCALE. FLOOR PLANS THAT INCLUDE: WINDOWS, DOORS, AND FIXTURES SUCH AS WC, BATH, SINK, SHOWER, ETC.',
        },
        {
            module: '4',
            topics: 'SECTIONS AND SECTIONAL VIEWS OF RIGHT ANGULAR SOLIDS: COVERING, PRISM, CYLINDER, PYRAMID, CONE – AUXILIARY VIEWS; DEVELOPMENT OF SURFACES OF RIGHT REGULAR SOLIDS- PRISM, PYRAMID, CYLINDER AND CONE; DRAW THE SECTIONAL ORTHOGRAPHIC VIEWS OF GEOMETRICAL SOLIDS, OBJECTS FROM INDUSTRY AND DWELLINGS (FOUNDATION TO SLAB ONLY) ',
        },
        {
            module: '5',
            topics: 'ISOMETRIC PROJECTIONS: PRINCIPLES OF ISOMETRIC PROJECTION – ISOMETRIC SCALE, ISOMETRIC VIEWS, CONVENTIONS; ISOMETRIC VIEWS OF LINES, PLANES, SIMPLE AND COMPOUND SOLIDS; CONVERSION OF ISOMETRIC VIEWS TO ORTHOGRAPHIC VIEWS AND VICE-VERSA, CONVENTIONS ',
        },
        {
            module: '6',
            topics: 'OVERVIEW OF COMPUTER GRAPHICS: LISTING THE COMPUTER TECHNOLOGIES THAT IMPACT ON GRAPHICAL COMMUNICATION, DEMONSTRATING KNOWLEDGE OF THE THEORY OF CAD SOFTWARE [SUCH AS: THE MENU SYSTEM, TOOLBARS (STANDARD, OBJECT PROPERTIES, DRAW, MODIFY AND DIMENSION), DRAWING AREA (BACKGROUND, CROSSHAIRS, COORDINATE SYSTEM), DIALOG BOXES AND WINDOWS, SHORTCUT MENUS (BUTTON BARS), THE COMMAND LINE (WHERE APPLICABLE), THE STATUS BAR, DIFFERENT METHODS OF ZOOM AS USED IN CAD, SELECT AND ERASE OBJECTS.; ISOMETRIC VIEWS OF LINES, PLANES, SIMPLE AND COMPOUND SOLIDS]',
        },
        {
            module: '7',
            topics: 'CUSTOMISATION& CAD DRAWING: CONSISTING OF SET UP OF THE DRAWING PAGE AND THE PRINTER, INCLUDING SCALE SETTINGS, SETTING UP OF UNITS AND DRAWING LIMITS; ISO AND ANSI STANDARDS FOR COORDINATE DIMENSIONING AND TOLERANCING; ORTHOGRAPHIC CONSTRAINTS, SNAP TO OBJECTS MANUALLY AND AUTOMATICALLY; PRODUCING DRAWINGS BY USING VARIOUS COORDINATE INPUT ENTRY METHODS TO DRAW STRAIGHT LINES, APPLYING VARIOUS WAYS OF DRAWING CIRCLES.',
        },
        {
            module: '8',
            topics: 'ANNOTATIONS, LAYERING & OTHER FUNCTIONS: COVERING APPLYING DIMENSIONS TO OBJECTS, APPLYING ANNOTATIONS TO DRAWINGS; SETTING UP AND USE OF LAYERS, LAYERS TO CREATE DRAWINGS, CREATE, EDIT AND USE CUSTOMIZED LAYERS; CHANGING LINE LENGTHS THROUGH MODIFYING EXISTING LINES (EXTEND/LENGTHEN); PRINTING DOCUMENTS TO PAPER USING THE PRINT COMMAND; ORTHOGRAPHIC PROJECTION TECHNIQUES; DRAWING SECTIONAL VIEWS OF COMPOSITE RIGHT REGULAR GEOMETRIC SOLIDS AND PROJECT THE TRUE SHAPE OF THE SECTIONED SURFACE; DRAWING ANNOTATION, COMPUTER-AIDED DESIGN (CAD) SOFTWARE MODELING OF PARTS AND ASSEMBLIES. PARAMETRIC AND NON-PARAMETRIC SOLID, SURFACE, AND WIREFRAME MODELS. PART EDITING AND TWO-DIMENSIONAL DOCUMENTATION OF MODELS. PLANAR PROJECTION THEORY, INCLUDING SKETCHING OF PERSPECTIVE, ISOMETRIC, MULTIVIEW, AUXILIARY, AND SECTION VIEWS. SPATIAL VISUALIZATION EXERCISES. DIMENSIONING GUIDELINES, TOLERANCING TECHNIQUES; DIMENSIONING AND SCALE MULTI VIEWS OF DWELLING.',
        },
        {
            module: '9',
            topics: 'DEMONSTRATION OF A SIMPLE TEAM DESIGN PROJECT THAT ILLUSTRATES: GEOMETRY AND TOPOLOGY OF ENGINEERED COMPONENTS: CREATION OF ENGINEERING MODELS AND THEIR PRESENTATION IN STANDARD 2D BLUEPRINT FORM AND AS 3D WIREFRAME AND SHADED SOLIDS; MESHED TOPOLOGIES FOR ENGINEERING ANALYSIS AND TOOLPATH GENERATION FOR COMPONENT MANUFACTURE; GEOMETRIC DIMENSIONING AND TOLERANCING; USE OF SOLID-MODELING SOFTWARE FOR CREATING ASSOCIATIVE MODELS AT THE COMPONENT AND ASSEMBLY LEVELS. FLOOR PLANS THAT INCLUDE: WINDOWS, DOORS, AND FIXTURES SUCH AS WC, BATH, SINK, SHOWER, ETC. APPLYING COLOUR CODING ACCORDING TO BUILDING DRAWING PRACTICE; DRAWING SECTIONAL ELEVATION SHOWING FOUNDATION TO CEILING; INTRODUCTION TO BUILDING INFORMATION MODELLING (BIM). ',
        },
    ],
    books: [
        { name: 'ENGINEERING DRAWING', author: 'BHATT N.D., PANCHAL V.M. & INGLE P.R.' },
        { name: 'ENGINEERING DRAWING AND COMPUTER GRAPHICS', author: 'SHAH, M.B. &RANA B.C.' },
        { name: 'ENGINEERING GRAPHICS', author: 'AGRAWAL B. & AGRAWAL C. M.' },
        { name: 'TEXT BOOK ON ENGINEERING DRAWING', author: 'NARAYANA, K.L. & P KANNAIAH' },
    ],

    outcomes: [
        'ALL PHASES OF MANUFACTURING OR CONSTRUCTION REQUIRE THE CONVERSION OF NEW IDEAS AND DESIGN CONCEPTS INTO THE BASIC LINE LANGUAGE OF GRAPHICS. THEREFORE, THERE ARE MANY AREAS (CIVIL, MECHANICAL, ELECTRICAL, ARCHITECTURAL AND INDUSTRIAL) IN WHICH THE SKILLS OF THE CAD TECHNICIANS PLAY MAJOR ROLES IN THE DESIGN AND DEVELOPMENT OF NEW PRODUCTS OR CONSTRUCTION. STUDENTS PREPARE FOR ACTUAL WORK SITUATIONS THROUGH PRACTICAL TRAINING IN A NEW STATE-OF-THE-ART COMPUTER DESIGNED CAD LABORATORY USING ENGINEERING SOFTWARE',
    ],
};
